# Makefile con comandos básicos de desarrollo
run: ## Ejecuta el servidor en modo local
	go run ./cmd/server

build: ## Compila el binario
	go build -o server ./cmd/server

tidy: ## Limpia dependencias
	go mod tidy

test: ## Ejecuta todos los tests
	go test ./... -cover

docker-build: ## Construye imagen docker
	docker build -t password-danie-backend ./backend

docker-run: ## Levanta docker compose
	docker compose up --build
